# Generated by Django 5.1.6 on 2025-02-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_usercredit_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='is_affiliate',
            field=models.BooleanField(default=False),
        ),
    ]
