# Generated by Django 5.1.6 on 2025-02-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_pixwithdrawal_approved_at_pixwithdrawal_approved_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PixWithdrawal',
        ),
    ]
