# Generated by Django 5.1.6 on 2025-02-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='referral_link',
            field=models.URLField(blank=True),
        ),
    ]
