# Generated by Django 5.1.6 on 2025-02-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_usercredit_level'),
        ('accounts', '0004_user'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuarios',
        ),
    ]
