# Generated by Django 5.1.6 on 2025-02-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_withdrawal_pix_key_withdrawal_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliate',
            options={'verbose_name_plural': 'Afiliados'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name_plural': 'Rastreio de Afiliados'},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'verbose_name_plural': 'Saques'},
        ),
    ]
